"""empty message

Revision ID: 99358ba41a7e
Revises: 
Create Date: 2020-03-01 13:38:45.032693

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '99358ba41a7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_fitness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('pace', sa.Time(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_heartrate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_fitness')
    # ### end Alembic commands ###
