"""empty message

Revision ID: e8c57a40ef6d
Revises: 
Create Date: 2020-02-29 17:22:54.511784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c57a40ef6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_fitness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('pace', sa.Time(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_fitness')
    # ### end Alembic commands ###
